name: Push to gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - run: yarn
      - run: yarn run publish
      - name: add date
        run: |
          echo TIME=`date '+%Y-%m-%d-%H:%M:%S %Z'` >> $GITHUB_ENV
          echo $TIME
      - name: Push to gh-pages branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
          committer: Mandakara Sadewa <mdswa@zxce3.net>
          author: Mandakara Sadewa <mdswa@zxce3.net>
          commit_message: "Update `${{ env.TIME }}`"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
