name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - run: yarn
      - run: yarn run publish
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
          committer: Mandakara Sadewa <mdswa@zxce3.net>
          author: Mandakara Sadewa <mdswa@zxce3.net>
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}